version: "3"

services:
  traefik:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        host_name: ${DOMAIN_NAME}
        frontend_prefix: ${PUBLIC_URL}
        backend_prefix: ${DOMAIN_SUBDIRECTORY}
    image: metagrid_production_traefik
    ports:
      - "0.0.0.0:80:80"
